---
title: "Kimbe Predator Graphics"
author: "Ben Cresswell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
 html_document:
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 4
    fig_width: 4
    highlight: textmate
    theme: spacelab
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=TRUE, warnings=FALSE, message=FALSE}
knitr::opts_chunk$set(root.dir = "~/OneDrive - James Cook University/Ben PhD/Data & analysis/KimbePreds/", echo = TRUE)
#rm(list=ls())
getwd()
```


# Load relevant packates
```{r packages}
library(readxl)
library(gridExtra)
library(sjPlot)
library(patchwork)
library(tidyverse)
```


# Create themes and lists to make plotting simpler later
```{r lists-themes, include=FALSE}
resultstheme <-
  theme_classic()+
  theme(legend.position = "none")+
  theme(axis.title.x = element_text(family="Arial", size=10, colour = 'black', vjust = -0.5))+
  theme(axis.text.x = element_text(family="Arial", size= 10, colour = 'black', angle=0, vjust = 0))+
        #axis.title.y = element_text(family="Arial", size=10, colour = 'black', vjust=0),
        #axis.text.y = element_text(family="Arial", size= 10, colour = 'black'))+
  theme(axis.line = element_blank(), panel.border = element_rect(size = 1, fill = "transparent")) 



#nulltheme <- 
 # theme_classic()+
  #theme(axis.text.x = element_blank())

#emmeanslist <- list(
 # geom_pointrange(aes(ymin=lower.CL,  ymax=upper.CL)))
  #geom_point(aes(shape = Reeftype),stat="identity", colour="black", size = 4)+
  #scale_shape_manual(values=c(24, 21, 22))+                       # had to adapt Kimbe pch scheme
  #scale_fill_manual(values=c("#35978F","#436EEE","#DFC27D"))




contrastslist <- list(
  geom_pointrange(aes(ymin=lower.CL,  ymax=upper.CL)),
  geom_hline(yintercept = 0, linetype='dashed'),
  ylab(''),
  scale_y_continuous(position = "right"))
```


# Abundance
```{r abun-plot}
# Load data
load("../../data/abunplotdata.RData")

# Tweak contrast labels so they will fit on subsequent figure
abunplotdata$contrasts$contrast <- dplyr::recode(abunplotdata$contrasts$contrast,
       `Pinnacle - Offshore` = 'P-O',
       `Pinnacle - Nearshore` = 'P-N',
       `Offshore - Nearshore` = 'O-N')

# Relevel contrasts so they show up in a logical order
abunplotdata$contrasts <- abunplotdata$contrasts %>% 
  mutate(contrast = factor(contrast, levels= c("P-O", "P-N", "O-N")))

# Rename (recode) the Reeftypes in emmeans so that you get "level" figures
abunplotdata$emmeans$Reeftype <- dplyr::recode(abunplotdata$emmeans$Reeftype,
                                          `Pinnacle` = 'P',
                                          `Offshore` = 'O',
                                          `Nearshore` = 'N')

# And convert back to emm object
abunplotdata <- abunplotdata %>% 
  as.list

# Check
abunplotdata

# Create emmeans figure
abunplotresults <- 
  ggplot(abunplotdata$emmeans, aes(y=response,  x=Reeftype, fill=Reeftype)) +
  ylab('Abundance (n)\n')+
  xlab(NULL)+
  geom_linerange(aes(ymin=lower.CL, ymax=upper.CL), width=.2)+
  geom_point(aes(shape = Reeftype, fill= Reeftype), colour="black", size = 4)+
  scale_shape_manual(values=c(24, 21, 22))+                       # had to adapt Kimbe pch scheme
  scale_fill_manual(values=c("#35978F","#436EEE","#DFC27D"))+
  theme_classic()+
  theme(legend.position = "none")+
  theme(axis.text.x = element_blank())+
  #theme(axis.title.x = element_text(family="Arial", size=10, colour = 'black', vjust = -0.5))+
  #theme(axis.text.x = element_text(family="Arial", size= 10, colour = 'black', angle=0, vjust = 0))+
  theme(axis.title.y = element_text(family="Arial", size=10, colour = 'black', vjust=0))+
  theme(axis.text.y = element_text(family="Arial", size= 10, colour = 'black'))+
  theme(axis.line = element_blank(), panel.border = element_rect(size = 1, fill = "transparent")) +
  annotate("text", x = 0.6, y = 23, label = "a")

abunplotresults

# Create contrasts figure
abunplotcontrasts <- 
  ggplot(abunplotdata$contrasts, aes(y=estimate,  x=contrast)) +
  geom_linerange(aes(ymin=lower.CL,  ymax=upper.CL)) +
  geom_point(colour="black", size = 4)+
  geom_hline(yintercept = 0, linetype='dashed') +
  scale_y_continuous(position = "right")+
  ylab('') +
  xlab(NULL)+
  theme_classic()+
  theme(axis.text.x = element_blank())+
  #theme(axis.title.x = element_text(family="Arial", size=10, colour = 'black', vjust = -0.5))+
  #theme(axis.text.x = element_text(family="Arial", size= 10, colour = 'black', angle=0, vjust = 0))+
  theme(axis.title.y = element_text(family="Arial", size=10, colour = 'black', vjust=0))+
  theme(axis.text.y = element_text(family="Arial", size= 10, colour = 'black'))+
  theme(axis.line = element_blank(), panel.border = element_rect(size = 1, fill = "transparent")) +
  annotate("text", x = 3.4, y = 20, label = "d")

abunplotcontrasts

# Plot together
# Patchwork
abunfig <- abunplotresults + abunplotcontrasts



abunfig



# Save
#ggsave(abunfig, filename= '../../output/rfigures/abun_fig_col.png', width=7,  height=2, dpi = 600 )
```


# Biomass

```{r abun-plot}
# Load data
load(file='../../data/biomplotdata.RData')

# Tweak contrast labels so they will fit on subsequent figure
biomplotdata$contrasts$contrast <- dplyr::recode(biomplotdata$contrasts$contrast,
       `Pinnacle - Offshore` = 'P-O',
       `Pinnacle - Nearshore` = 'P-N',
       `Offshore - Nearshore` = 'O-N')

# Relevel contrasts so they show up in a logical order
biomplotdata$contrasts <- biomplotdata$contrasts %>% 
  mutate(contrast = factor(contrast, levels= c("P-O", "P-N", "O-N")))

# Rename (recode) the Reeftypes in emmeans so that you get "level" figures
biomplotdata$emmeans$Reeftype <- dplyr::recode(biomplotdata$emmeans$Reeftype,
                                          `Pinnacle` = 'P',
                                          `Offshore` = 'O',
                                          `Nearshore` = 'N')
# And convert back to emm object
biomplotdata <- biomplotdata %>% 
  as.list

# Check
biomplotdata

# Create emmeans figure
biomplotresults <- 
  ggplot(biomplotdata$emmeans, aes(y=response,  x=Reeftype)) +
  ylab('Biomass (kg)\n')+
  xlab(NULL)+
  geom_linerange(aes(ymin=lower.CL, ymax=upper.CL), width=.2)+
  geom_point(aes(shape = Reeftype, fill= Reeftype), colour="black", size = 4)+
  scale_shape_manual(values=c(24, 21, 22))+                       # had to adapt Kimbe pch scheme
  scale_fill_manual(values=c("#35978F","#436EEE","#DFC27D"))+
  theme_classic()+
  theme(legend.position = "none")+
  theme(axis.text.x = element_blank())+
  #theme(axis.title.x = element_text(family="Arial", size=10, colour = 'black', vjust = -0.5))+
  #theme(axis.text.x = element_text(family="Arial", size= 10, colour = 'black', angle=0, vjust = 0))+
  theme(axis.title.y = element_text(family="Arial", size=10, colour = 'black', vjust=0))+
  theme(axis.text.y = element_text(family="Arial", size= 10, colour = 'black'))+
  theme(axis.line = element_blank(), panel.border = element_rect(size = 1, fill = "transparent")) +
  annotate("text", x = 0.6, y = 34, label = "b")


# Create contrasts figure
biomplotcontrasts <- 
  ggplot(biomplotdata$contrasts, aes(y=estimate,  x=contrast)) +
  geom_linerange(aes(ymin=lower.CL,  ymax=upper.CL)) +
  geom_point(colour="black", size = 4)+
  geom_hline(yintercept = 0, linetype='dashed') +
  scale_y_continuous(position = "right")+
  ylab('') +
  xlab(NULL)+
  theme_classic()+
  theme(axis.text.x = element_blank())+
  #theme(axis.title.x = element_text(family="Arial", size=10, colour = 'black', vjust = -0.5))+
  #theme(axis.text.x = element_text(family="Arial", size= 10, colour = 'black', angle=0, vjust = 0))+
  theme(axis.title.y = element_text(family="Arial", size=10, colour = 'black', vjust=0))+
  theme(axis.text.y = element_text(family="Arial", size= 10, colour = 'black'))+
  theme(axis.line = element_blank(), panel.border = element_rect(size = 1, fill = "transparent")) +
  annotate("text", x = 3.4, y = 30, label = "e")


# Plot together
biomfig <- 
  biomplotresults + biomplotcontrasts
biomfig
# Save
#ggsave(biomfig, filename= '../../output/rfigures/biomass_fig.png', width=7,  height=2, dpi = 600 )

```

# Note

# Species richness
Not included in final figures


# Shannon Weiner diversity
```{r shannon-plot}
# Load data
load("../../data/shanplotdata.RData")

# Tweak contrast labels so they will fit on subsequent figure
shanplotdata$contrasts$contrast <- dplyr::recode(shanplotdata$contrasts$contrast,
                                          `Pinnacle - Offshore` = 'P-O',
                                          `Pinnacle - Nearshore` = 'P-N',
                                          `Offshore - Nearshore` = 'O-N')


# Relevel contrasts so they show up in a logical order
shanplotdata$contrasts <- shanplotdata$contrasts %>% 
  mutate(contrast = factor(contrast, levels= c("P-O", "P-N", "O-N")))

# Rename (recode) the Reeftypes in emmeans so that you get "level" figures
shanplotdata$emmeans$Reeftype <- dplyr::recode(shanplotdata$emmeans$Reeftype,
                                        `Pinnacle` = 'P',
                                        `Offshore` = 'O',
                                          `Nearshore` = 'N')
# And convert back to emm object
shanplotdata <- shanplotdata %>% 
  as.list

# Check
shanplotdata

# Create emmeans figure
shanplotresults <- 
  ggplot(shanplotdata$emmeans, aes(y=response,  x=Reeftype)) +
  ylab('Diversity (H)\n')+
  xlab('Reef type')+
  geom_linerange(aes(ymin=lower.CL, ymax=upper.CL), width=.2)+
  geom_point(aes(shape = Reeftype, fill= Reeftype), colour="black", size = 4)+
  scale_shape_manual(values=c(24, 21, 22))+                       # had to adapt Kimbe pch scheme
  scale_fill_manual(values=c("#35978F","#436EEE","#DFC27D"))+
  theme_classic()+
  theme(legend.position = "none")+
  #theme(axis.text.x = element_blank())+
  theme(axis.title.x = element_text(family="Arial", size=10, colour = 'black', vjust = -0.5))+
  theme(axis.text.x = element_text(family="Arial", size= 10, colour = 'black', angle=0, vjust = 0))+
  theme(axis.title.y = element_text(family="Arial", size=10, colour = 'black', vjust=0))+
  theme(axis.text.y = element_text(family="Arial", size= 10, colour = 'black'))+
  theme(axis.line = element_blank(), panel.border = element_rect(size = 1, fill = "transparent")) +
  annotate("text", x = 0.6, y = 1.4, label = "c")


# Create contrasts figure
shanplotcontrasts <- 
  ggplot(shanplotdata$contrasts, aes(y=estimate,  x=contrast)) +
  geom_linerange(aes(ymin=lower.CL,  ymax=upper.CL)) +
  geom_point(colour="black", size = 4)+
  geom_hline(yintercept = 0, linetype='dashed') +
  scale_y_continuous(position = "right")+
  ylab('') +
  xlab('Contrasts')+
  theme_classic()+
  theme(axis.text.x = element_blank())+
  theme(axis.title.x = element_text(family="Arial", size=10, colour = 'black', vjust = -0.5))+
  theme(axis.text.x = element_text(family="Arial", size= 10, colour = 'black', angle=0, vjust = 0))+
  theme(axis.title.y = element_text(family="Arial", size=10, colour = 'black', vjust=0))+
  theme(axis.text.y = element_text(family="Arial", size= 10, colour = 'black'))+
  theme(axis.line = element_blank(), panel.border = element_rect(size = 1, fill = "transparent")) +
  annotate("text", x = 3.4, y = 1.25, label = "f")

# Plot together in patchwork
shanfig <- shanplotresults + shanplotcontrasts
shanfig
# Save
#ggsave(shanfig, filename= '../../output/rfigures/shan_fig.png', width=7,  height=2, dpi = 500 )
```



# Combined  figure
```{r graph-combined, fig.height = 5, fig.width = 8}
# Using patchwork not gridarrange (lines up axes better)
mainfig <- abunfig / biomfig / shanfig
mainfig

#ggsave(mainfig, filename= '../../output/rfigures/main_fig_goldrat.tiff',  width = 174, height = 107, units = "mm", dpi = 1200)

citation('ggvenn')
```



