---
title: "Kimbe Predator Graphics"
author: "Ben Cresswell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
 html_document:
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 4
    fig_width: 4
    highlight: textmate
    theme: spacelab
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=TRUE, warnings=FALSE, message=FALSE}
knitr::opts_chunk$set(root.dir = "~/OneDrive - James Cook University/Ben PhD/Data & analysis/KimbePreds/", echo = TRUE)
rm(list=ls())
getwd()
```


# Load relevant packates
```{r packages}
library(readxl)
library(gridExtra)
library(sjPlot)
library(patchwork)
library(tidyverse)
```


# Create themes and lists to make plotting simpler later
```{r lists-themes, include=FALSE}
resultstheme <-
  theme_classic()+
  theme(axis.title.x = element_text(family="Arial", size=10, colour = 'black', vjust = -0.5),
        axis.title.y = element_text(family="Arial", size=10, colour = 'black', vjust=0),
        axis.text.x = element_text(family="Arial", size= 10, colour = 'black', angle=0, vjust = 0),
        axis.text.y = element_text(family="Arial", size= 10, colour = 'black'))

nulltheme <- 
  theme_classic()+
  theme(axis.text.x = element_blank())

emmeanslist <- list(
  geom_pointrange(aes(ymin=lower.CL,  ymax=upper.CL)))

contrastslist <- list(
  geom_pointrange(aes(ymin=lower.CL,  ymax=upper.CL)),
  geom_hline(yintercept = 0, linetype='dashed'),
  ylab(''),
  scale_y_continuous(position = "right"))
```


# Abundance
```{r abun-plot}
# Load data
load("../../data/abunplotdata.RData")

# Tweak contrast labels so they will fit on subsequent figure
abunplotdata$contrasts$contrast <- dplyr::recode(abunplotdata$contrasts$contrast,
       `Pinnacle - Offshore` = 'P-O',
       `Pinnacle - Nearshore` = 'P-N',
       `Offshore - Nearshore` = 'O-N')

# Relevel contrasts so they show up in a logical order
abunplotdata$contrasts <- abunplotdata$contrasts %>% 
  mutate(contrast = factor(contrast, levels= c("P-O", "P-N", "O-N")))

# Rename (recode) the Reeftypes in emmeans so that you get "level" figures
abunplotdata$emmeans$Reeftype <- dplyr::recode(abunplotdata$emmeans$Reeftype,
                                          `Pinnacle` = 'P',
                                          `Offshore` = 'O',
                                          `Nearshore` = 'N')

# And convert back to emm object
abunplotdata <- abunplotdata %>% 
  as.list

# Check
abunplotdata

# Create emmeans figure
abunplotresults <- ggplot(abunplotdata$emmeans, aes(y=response,  x=Reeftype)) +
  ylab('\nAbundance\n(n)\n')+
  xlab(NULL)+
  resultstheme+
  theme(axis.text.x = element_blank())+
  emmeanslist+
  annotate("text", x = 0.7, y = 25, label = "A")

# Create contrasts figure
abunplotcontrasts <- ggplot(abunplotdata$contrasts, aes(y=estimate,  x=contrast)) +
  resultstheme+
  theme(axis.text.x = element_blank())+
  contrastslist+
  xlab(NULL)

# Plot together
abunfig <- grid.arrange(abunplotresults, abunplotcontrasts, nrow=1)

# Save
#ggsave(abunfig, filename= '../../output/rfigures/abun_fig.png', width=7,  height=2, dpi = 500 )
```


# Biomass

```{r abun-plot}
# Load data
load(file='../../data/biomplotdata.RData')

# Tweak contrast labels so they will fit on subsequent figure
biomplotdata$contrasts$contrast <- dplyr::recode(biomplotdata$contrasts$contrast,
       `Pinnacle - Offshore` = 'P-O',
       `Pinnacle - Nearshore` = 'P-N',
       `Offshore - Nearshore` = 'O-N')

# Relevel contrasts so they show up in a logical order
biomplotdata$contrasts <- biomplotdata$contrasts %>% 
  mutate(contrast = factor(contrast, levels= c("P-O", "P-N", "O-N")))

# Rename (recode) the Reeftypes in emmeans so that you get "level" figures
biomplotdata$emmeans$Reeftype <- dplyr::recode(biomplotdata$emmeans$Reeftype,
                                          `Pinnacle` = 'P',
                                          `Offshore` = 'O',
                                          `Nearshore` = 'N')
# And convert back to emm object
biomplotdata <- biomplotdata %>% 
  as.list

# Check
biomplotdata

# Create emmeans figure
biomplotresults <- ggplot(biomplotdata$emmeans, aes(y=response,  x=Reeftype)) +
  ylab('\nBiomass\n(kg)\n')+
  xlab('Reef type')+
  resultstheme+
  emmeanslist+
  annotate("text", x = 0.7, y = 32, label = "B")


# Create contrasts figure
biomplotcontrasts <- ggplot(biomplotdata$contrasts, aes(y=estimate,  x=contrast)) +
  resultstheme+
  contrastslist+
  xlab('Contrasts')+
  contrastslist


# Plot together
biomfig <- grid.arrange(biomplotresults, biomplotcontrasts, nrow=1)

# Save
ggsave(biomfig, filename= '../../output/rfigures/biomass_fig.png', width=7,  height=2, dpi = 500 )


```


# Species richness
```{r rich-plot}
# Load data
load("../../data/richplotdata.RData")

# Tweak contrast labels so they will fit on subsequent figure
richplotdata$contrasts$contrast <- dplyr::recode(richplotdata$contrasts$contrast,
       `Pinnacle - Offshore` = 'P-O',
       `Pinnacle - Nearshore` = 'P-N',
       `Offshore - Nearshore` = 'O-N')

# Relevel contrasts so they show up in a logical order
richplotdata$contrasts <- richplotdata$contrasts %>% 
  mutate(contrast = factor(contrast, levels= c("P-O", "P-N", "O-N")))


# Rename (recode) the Reeftypes in emmeans so that you get "level" figures
richplotdata$emmeans$Reeftype <- dplyr::recode(richplotdata$emmeans$Reeftype,
                                        `Pinnacle` = 'P',
                                       `Offshore` = 'O',
                                          `Nearshore` = 'N')


# And convert back to emm object
richplotdata <- richplotdata %>% 
  as.list

# Check
richplotdata

# Create emmeans figure
richplotresults <- ggplot(richplotdata$emmeans, aes(y=rate,  x=Reeftype)) +
  ylab('Species\nrichness\n(no. spp.)\n')+
  xlab(NULL)+
  resultstheme+
  theme(axis.text.x = element_blank())+
  emmeanslist+
  annotate("text", x = 0.7, y = 7.7, label = "A")


# Create contrasts figure
richplotcontrasts <- ggplot(richplotdata$contrasts, aes(y=estimate,  x=contrast)) +
  resultstheme+
  theme(axis.text.x = element_blank())+
  contrastslist+
  xlab(NULL)

# Plot together
richfig <- grid.arrange(richplotresults, richplotcontrasts, nrow=1)

# Save
ggsave(richfig, filename= '../../output/rfigures/rich_fig.png', width=7,  height=2, dpi = 500 )
```



# Shannon Weiner diversity
```{r shannon-plot}
# Load data
load("../../data/shanplotdata.RData")

# Tweak contrast labels so they will fit on subsequent figure
shanplotdata$contrasts$contrast <- dplyr::recode(shanplotdata$contrasts$contrast,
                                          `Pinnacle - Offshore` = 'P-O',
                                          `Pinnacle - Nearshore` = 'P-N',
                                          `Offshore - Nearshore` = 'O-N')


# Relevel contrasts so they show up in a logical order
shanplotdata$contrasts <- shanplotdata$contrasts %>% 
  mutate(contrast = factor(contrast, levels= c("P-O", "P-N", "O-N")))

# Rename (recode) the Reeftypes in emmeans so that you get "level" figures
shanplotdata$emmeans$Reeftype <- dplyr::recode(shanplotdata$emmeans$Reeftype,
                                        `Pinnacle` = 'P',
                                        `Offshore` = 'O',
                                          `Nearshore` = 'N')
# And convert back to emm object
shanplotdata <- shanplotdata %>% 
  as.list

# Check
shanplotdata

# Create emmeans figure
shanplotresults <- ggplot(shanplotdata$emmeans, aes(y=rate,  x=Reeftype)) +
  ylab('Shannon-\nWiener\n(H)\n')+
  xlab('Reef type')+
  resultstheme+
  emmeanslist+
  annotate("text", x = 0.7, y = 1.5, label = "B")


# Create contrasts figure
shanplotcontrasts <- ggplot(shanplotdata$contrasts, aes(y=estimate,  x=contrast)) +
  xlab('Contrasts')+
  resultstheme+
  contrastslist

# Plot together
shanfig <- grid.arrange(shanplotresults, shanplotcontrasts, nrow=1)

# Save
ggsave(shanfig, filename= '../../output/rfigures/shan_fig.png', width=7,  height=2, dpi = 500 )
```



# Combined abundance and biomass figure
```{r graph-abunbiom}
# Using patchwork not gridarrange (lines up axes better)
abunbiomfig <- abunplotresults + abunplotcontrasts + biomplotresults + biomplotcontrasts +
  plot_layout(ncol = 2)
abunbiomfig

ggsave(abunbiomfig, filename= '../../output/rfigures/abun_biom_fig.png', width=5,  height=4, dpi = 500 )

```


# Combined abundance and biomass figure
```{r graph-abunbiom}
# Using patchwork not gridarrange (lines up axes better)
divfig <- richplotresults + richplotcontrasts + shanplotresults + shanplotcontrasts +
  plot_layout(ncol = 2)
divfig

ggsave(divfig, filename= '../../output/rfigures/div_fig.png', width=5,  height=4, dpi = 500 )

```


# PCoA on Community Differences

```{r-PCoA}















```


# Venn diagram

```{r venn}

# Load data
alltaxa <- read_excel("../../output/rtables/taxa_presence_absence.xlsx")













```

